- name: Install build dependencies (Linux)
  if: runner.os == 'Linux'
  run: |
    sudo apt-get update
    sudo apt-get update
    # Install latest GCC (currently GCC 13)
    sudo apt-get install -y cmake gcc g++

- name: Rust Cache
  uses: Swatinem/rust-cache@v2
  with:
    prefix-key: "v1-rust"
    shared-key: "${{ matrix.target }}-build"
    cache-targets: "true"
    cache-on-failure: "true"
    cache-all-crates: "true"
    save-if: ${{ github.ref == 'refs/heads/master' }}
    workspaces: |
      . -> target
