name: Publish Docker image

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Parse plan
        id: plan
        run: |
          # Extract the tag from plan.outputs.tag
          echo "Plan content for debugging:"
          echo '${{ inputs.plan }}' | jq .
          TAG=$(echo '${{ inputs.plan }}' | jq -r '.tag')
          VERSION=$(echo '${{ inputs.plan }}' | jq -r '.releases[0].app_version')
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.plan.outputs.TAG }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            bitping/distributed-metrics:latest
            bitping/distributed-metrics:${{ steps.plan.outputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
